name: first-workflow
on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: clone workflow1 repository
     uses: actions/checkout@v3
     with: 
      repository: saradha92/workflow1
      path: workflow/clone/master
      ref: master
 test:
  runs-on: ubuntu-latest
  steps: 
   - name: status
     run: echo "successfull"
  
     
   
